development:
  adapter: async
  url: <%= ENV["REDIS_URL"] %>

test:
  adapter: test
  url: <%= ENV["REDIS_URL"] %>

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: parser_eml_production
