default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "123456") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "parser_db") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_TEST", "parser_db_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_PROD", "parser_db_production") %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "123456") %>
